### ISSUE TITLE
Luna why?

### ISSUE THREAD

**Issue by primitt** [LunaWasFlagged/goinospammer#2]
Why are you doing this? Does it benefit you?

**Comment by primitt** [comment]
https://i.imgur.com/DNqoZwk.png luna, this is my fault XDDDD i closed the ssh window without turning on the screen and forgot about it for a while XDDD

**Comment by LunaWasFlagged** [comment]
> why?

read the readme.

**Comment by primitt** [comment]
> > why?
> 
> read the readme.

I see, but why do you think duino-coin as a shitcoin, if that's the case can you go spam bitcoin? If you think its a shitcoin, what can we do to make it better XD, you want to go use eth, go use eth, but the internet does not change if duinocoin dies XD

**Comment by primitt** [comment]
Luna, im not mad lol, i just want to know how we can be better.

**Comment by primitt** [comment]
Well imma just close this lol

**Comment by primitt** [comment]
> > I see, but why do you think duino-coin as a shitcoin, if that's the case can you go spam bitcoin? If you think its a shitcoin, what can we do to make it better XD, you want to go use eth, go use eth, but the internet does not change if duinocoin dies XD
> 
> There are multiple reasons why duinocoin is a shitcoin. It's managed by people that can't make a decentralized coin, meaning: someone does a oopsie on the main servers, and everything's down. (which has happened multiple times)
> The creators also don't really care much about their coin - they're going to make it required for you to send a photo of your mining rig for you to even mine. And the founder of it doesn't care about the bots - "free money"

So.... how can we become decentralized with mining with Arduinos? How can we give proper rewards?
